
const DATA = [
   {
    month: "January",
    year: 2015,
    income: 30.5,
    outcome: 22.8,
    indexYear: 0,
    indexMonth: 0,
   },
   {
    month: "February",
    year: 2015,
    income: 22.7,
    outcome: 19.3,
    indexYear: 0,
    indexMonth: 1,
   },
   {
    month: "March",
    year: 2015,
    income: 27.2,
    outcome: 10.3,
    indexYear: 0,
    indexMonth: 2,
   },
   {
    month: "April",
    year: 2015,
    income: 30.2,
    outcome: 14.6,
    indexYear: 0,
    indexMonth: 3,
   },
   {
    month: "May",
    year: 2015,
    income: 31.2,
    outcome: 15.7,
    indexYear: 0,
    indexMonth: 4,
   },
   {
    month: "June",
    year: 2015,
    income: 21.2,
    outcome: 20.9,
    indexYear: 0,
    indexMonth: 5,
   },
   {
    month: "July",
    year: 2015,
    income: 25.7,
    outcome: 21.3,
    indexYear: 0,
    indexMonth: 6,
   },
   {
    month: "August",
    year: 2015,
    income: 24.2,
    outcome: 8.3,
    indexYear: 0,
    indexMonth: 7,
   },
   {
    month: "September",
    year: 2015,
    income: 22.1,
    outcome: 15.2,
    indexYear: 0,
    indexMonth: 8,
   },
   {
    month: "October",
    year: 2015,
    income: 24.7,
    outcome: 12.1,
    indexYear: 0,
    indexMonth: 9,
   },
   {
    month: "November",
    year: 2015,
    income: 34.1,
    outcome: 10.3,
    indexYear: 0,
    indexMonth: 10,
   },
   {
    month: "December",
    year: 2015,
    income: 24.2,
    outcome: 23.3,
    indexYear: 0,
    indexMonth: 11,
   },
   {
    month: "January",
    year: 2016,
    income: 21.5,
    outcome: 18.8,
    indexYear: 1,
    indexMonth: 0,
   },
   {
    month: "February",
    year: 2016,
    income: 21.3,
    outcome: 25.9,
    indexYear: 1,
    indexMonth: 1,
   },
   {
    month: "March",
    year: 2016,
    income: 23.2,
    outcome: 18.9,
    indexYear: 1,
    indexMonth: 2,
   },
   {
    month: "April",
    year: 2016,
    income: 28.7,
    outcome: 14.6,
    indexYear: 1,
    indexMonth: 3,
   },
   {
    month: "May",
    year: 2016,
    income: 19.3,
    outcome: 10.4,
    indexYear: 1,
    indexMonth: 4,
   },
   {
    month: "June",
    year: 2016,
    income: 28.3,
    outcome: 22.9,
    indexYear: 1,
    indexMonth: 5,
   },
   {
    month: "July",
    year: 2016,
    income: 15.7,
    outcome: 18.3,
    indexYear: 1,
    indexMonth: 6,
   },
   {
    month: "August",
    year: 2016,
    income: 27.7,
    outcome: 29.3,
    indexYear: 1,
    indexMonth: 7,
   },
   {
    month: "September",
    year: 2016,
    income: 22.7,
    outcome: 17.5,
    indexYear: 1,
    indexMonth: 8,
   },
   {
    month: "October",
    year: 2016,
    income: 19.3,
    outcome: 17.5,
    indexYear: 1,
    indexMonth: 9,
   },
   {
    month: "November",
    year: 2016,
    income: 25.4,
    outcome: 21.2,
    indexYear: 1,
    indexMonth: 10,
   },
   {
    month: "December",
    year: 2016,
    income: 26.3,
    outcome: 17.8,
    indexYear: 1,
    indexMonth: 11,
   },
   {
    month: "January",
    year: 2017,
    income: 27.5,
    outcome: 22.8,
    indexYear: 2,
    indexMonth: 0,
   },
   {
    month: "February",
    year: 2017,
    income: 25.4,
    outcome: 22.1,
    indexYear: 2,
    indexMonth: 1,
   },
   {
    month: "March",
    year: 2017,
    income: 31.2,
    outcome: 26.1,
    indexYear: 2,
    indexMonth: 2,
   },
   {
    month: "April",
    year: 2017,
    income: 22.7,
    outcome: 16.3,
    indexYear: 2,
    indexMonth: 3,
   },
   {
    month: "May",
    year: 2017,
    income: 29.7,
    outcome: 17.3,
    indexYear: 2,
    indexMonth: 4,
   },
   {
    month: "June",
    year: 2017,
    income: 25.2,
    outcome: 21.4,
    indexYear: 2,
    indexMonth: 5,
   },
   {
    month: "July",
    year: 2017,
    income: 21,
    outcome: 19.3,
    indexYear: 2,
    indexMonth: 6,
   },
   {
    month: "August",
    year: 2017,
    income: 24.1,
    outcome: 17.2,
    indexYear: 2,
    indexMonth: 7,
   },
   {
    month: "September",
    year: 2017,
    income: 25.7,
    outcome: 11.3,
    indexYear: 2,
    indexMonth: 8,
   },
   {
    month: "October",
    year: 2017,
    income: 26.3,
    outcome: 12.3,
    indexYear: 2,
    indexMonth: 9,
   },
   {
    month: "November",
    year: 2017,
    income: 27,
    outcome: 13.2,
    indexYear: 2,
    indexMonth: 10,
   },
   {
    month: "December",
    year: 2017,
    income: 27.4,
    outcome: 18.1,
    indexYear: 2,
    indexMonth: 11,
   },
   {
    month: "January",
    year: 2018,
    income: 27.6,
    outcome: 19.6,
    indexYear: 3,
    indexMonth: 0,
   }
];

export {DATA};